"use client"

import React, { useState, useEffect } from 'react'
import { Save, Loader2, Shield, User, Globe, Mail, FileCode } from 'lucide-react'
import { api } from '@/lib/api'
import { cn } from '@/lib/utils'

export default function SettingsPage() {
  const [profile, setProfile] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [success, setSuccess] = useState(false)
  const [testing, setTesting] = useState(false)
  const [testResult, setTestResult] = useState<{success: boolean, message: string} | null>(null)

  useEffect(() => {
    async function loadProfile() {
      try {
        const profiles = await api.getProfiles()
        if (profiles.length > 0) {
          setProfile(profiles[0])
        }
      } catch (err) {
        console.error("Failed to load profile:", err)
      } finally {
        setLoading(false)
      }
    }
    loadProfile()
  }, [])

  const handleSave = async () => {
    if (!profile || !profile.id) {
      console.warn("No profile loaded to save")
      return
    }
    setSaving(true)
    setSuccess(false)
    try {
      await api.updateProfile(profile.id, {
        name: profile.name,
        company_context: profile.company_context,
        llm_model: profile.llm_model,
        llm_api_key: profile.llm_api_key
      })
      setSuccess(true)
      setTimeout(() => setSuccess(false), 3000)
    } catch (err) {
      console.error("Save failed:", err)
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-slate-500">
        <Loader2 className="animate-spin mr-2" />
        Loading Settings...
      </div>
    )
  }

  return (
    <div className="max-w-4xl mx-auto p-12 space-y-12">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold text-slate-900">User Settings</h1>
        <p className="text-slate-500">Manage your SA persona, global constraints, and integration security.</p>
      </header>

      <div className="grid grid-cols-3 gap-12">
        <aside className="space-y-1">
          <nav className="space-y-1">
            <button className="w-full flex items-center gap-3 px-4 py-2 text-sm font-semibold text-blue-600 bg-blue-50 rounded-lg">
              <User size={18} />
              SA Profile
            </button>
            <button className="w-full flex items-center gap-3 px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 rounded-lg">
              <Globe size={18} />
              Integrations
            </button>
            <button className="w-full flex items-center gap-3 px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 rounded-lg">
              <Shield size={18} />
              Security
            </button>
          </nav>
        </aside>

        <main className="col-span-2 space-y-8">
          <section className="bg-white p-8 rounded-xl border border-slate-200 shadow-sm space-y-6">
            <h3 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-4">Architect Persona</h3>
            
            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-slate-700">Persona Name</label>
                <input 
                  value={profile?.name || ''}
                  onChange={(e) => setProfile({...profile, name: e.target.value})}
                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-slate-700">Global Design Constraints</label>
                <textarea 
                  value={profile?.company_context || ''}
                  onChange={(e) => setProfile({...profile, company_context: e.target.value})}
                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all h-32 resize-none"
                  placeholder="Define your standard tech stack, security mandates, and architectural principles here. The agent will respect these across all projects."
                />
                <p className="text-[10px] text-slate-400">These constraints provide a baseline for all architectural snapshots generated by the agent.</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                    <label className="text-sm font-semibold text-slate-700">LLM Model</label>
                    <input 
                      value={profile?.llm_model || 'gemini/gemini-1.5-flash'}
                      onChange={(e) => setProfile({...profile, llm_model: e.target.value})}
                      className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                      placeholder="e.g. gemini/gemini-2.0-flash"
                    />
                </div>
                <div className="space-y-1.5">
                    <label className="text-sm font-semibold text-slate-700">LLM API Key</label>
                    <input 
                      type="password"
                      value={profile?.llm_api_key || ''}
                      onChange={(e) => setProfile({...profile, llm_api_key: e.target.value})}
                      className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-2.5 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                      placeholder="sk-..."
                    />
                </div>
              </div>
              
              <div className="flex items-center gap-4 pt-2">
                <button
                  onClick={async () => {
                    setTesting(true);
                    setTestResult(null);
                    try {
                      const res = await api.testConnection(profile.llm_model, profile.llm_api_key);
                      setTestResult({ success: true, message: res.message });
                    } catch (err: any) {
                      setTestResult({ success: false, message: err.message });
                    } finally {
                      setTesting(false);
                    }
                  }}
                  disabled={testing || !profile?.llm_model}
                  className="flex items-center gap-2 px-4 py-2 text-xs font-bold text-slate-700 bg-slate-100 hover:bg-slate-200 disabled:opacity-50 rounded-lg transition-all"
                >
                  {testing ? <Loader2 size={14} className="animate-spin" /> : <Globe size={14} />}
                  Test Connection
                </button>
                {testResult && (
                  <span className={cn(
                    "text-[10px] font-bold px-2 py-1 rounded",
                    testResult.success ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"
                  )}>
                    {testResult.message}
                  </span>
                )}
              </div>
            </div>

            <div className="pt-4 flex items-center justify-between">
              <p className={cn("text-xs font-medium transition-opacity", success ? "text-green-600 opacity-100" : "opacity-0")}>
                Settings saved successfully!
              </p>
              <button 
                onClick={handleSave}
                disabled={saving}
                className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2.5 rounded-lg text-sm font-bold shadow-md transition-all flex items-center gap-2"
              >
                {saving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}
                Save Changes
              </button>
            </div>
          </section>

          <section className="bg-white p-8 rounded-xl border border-slate-200 shadow-sm space-y-6">
             <h3 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-4">Upcoming Integrations</h3>
             <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-red-500">
                      <Mail size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">Gmail</span>
                   <span className="text-[10px] text-slate-400 mt-1 italic">OAuth Ingestion</span>
                </div>
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-blue-500">
                      <FileCode size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">Local Files</span>
                   <span className="text-[10px] text-green-600 mt-1 font-bold uppercase tracking-tighter">Active</span>
                </div>
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-purple-600">
                      <Globe size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">Slack</span>
                   <span className="text-[10px] text-slate-400 mt-1 italic">Webhooks</span>
                </div>
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-blue-700">
                      <Shield size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">MS Teams</span>
                   <span className="text-[10px] text-slate-400 mt-1 italic">OAuth Ingestion</span>
                </div>
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-blue-400">
                      <Globe size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">Confluence</span>
                   <span className="text-[10px] text-slate-400 mt-1 italic">API Token</span>
                </div>
                <div className="p-4 border border-slate-100 rounded-xl bg-slate-50/50 flex flex-col items-center text-center">
                   <div className="w-10 h-10 bg-white rounded-lg shadow-sm flex items-center justify-center mb-3 text-green-600">
                      <Globe size={20} />
                   </div>
                   <span className="text-sm font-bold text-slate-900">GDrive / SP</span>
                   <span className="text-[10px] text-slate-400 mt-1 italic">OAuth Ingestion</span>
                </div>
             </div>
          </section>
        </main>
      </div>
    </div>
  )
}
